# Generated by Django 4.1.2 on 2022-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(default="", max_length=20, unique=True)),
                ("username", models.CharField(max_length=12, unique=True)),
                ("user_can_edit", models.BooleanField(default=False)),
            ],
        ),
    ]
